CREATE DATABASE FinalProject;
USE FinalProject;
SET LANGUAGE 'us_english';
--DROP DATABASE FinalProject;

--CREACION DE TABLAS CON SUS LLAVES PRIMARIAS 
CREATE TABLE EMPLOYEE(
 id INT PRIMARY KEY IDENTITY,
 fullname VARCHAR (50),
 addres VARCHAR(100),
 email VARCHAR(50),
 id_type_employee INT,
 id_manager INT 
);

CREATE TABLE CITIZEN(
 dui INT PRIMARY KEY,
 fullname VARCHAR(50),
 email VARCHAR(50),
 addres VARCHAR(150),
 phone VARCHAR(20),
 id_department INT,
 id_municipality INT,
 id_type_citizen INT
);

CREATE TABLE CABIN(
 id INT PRIMARY KEY IDENTITY,
 email VARCHAR(50),
 manager_name VARCHAR(50),
 addres VARCHAR(100),
 phone VARCHAR(20),
 id_department INT,
 id_municipality INT
);

 CREATE TABLE APPOINTMENT(
 id_appointment INT PRIMARY KEY IDENTITY,
 hour_appointment VARCHAR(50),
 hour_arrived VARCHAR (50),
 hour_vaccunated VARCHAR (50),
 date_appointment DATE,
 id_cabin INT,
 id_citizen INT
);

CREATE TABLE MANAGER(
id INT PRIMARY KEY IDENTITY,
user_employee VARCHAR(50),
password_manager VARCHAR(50)
);

--TABLAS CATALOGOS

CREATE TABLE TYPE_EMPLOYEE(
id INT PRIMARY KEY IDENTITY,
employee VARCHAR(50)
);

CREATE TABLE DEPARTMENT(
id INT PRIMARY KEY IDENTITY,
department VARCHAR(50)
);

CREATE TABLE MUNICIPALITY(
id INT PRIMARY KEY IDENTITY,
municipality VARCHAR(50),
id_department INT
);

CREATE TABLE DISEASES(
id INT PRIMARY KEY IDENTITY,
diseases VARCHAR(50),
dui_citizen INT
);

CREATE TABLE TYPE_CITIZEN(
id INT PRIMARY KEY IDENTITY,
type_citizen VARCHAR(100)
);

CREATE TABLE SIDE_EFFECTS(
id INT PRIMARY KEY IDENTITY,
side_effect VARCHAR(50),
dui_citizen INT);

--TABLA RESULTANTE DE LA TRASFORMACION N:N
CREATE TABLE MANAGERXCABIN(
id_register INT PRIMARY KEY IDENTITY,
id_manager INT,
id_cabin INT,
date_time DATETIME
);


--CREACION DE LLAVES FORANEAS
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_TYPE_EMPLOYEE_EMPLOYEE
FOREIGN KEY (id_type_employee) REFERENCES TYPE_EMPLOYEE (id);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_MANAGER_EMPLOYEE
FOREIGN KEY (id_manager) REFERENCES MANAGER (id);

ALTER TABLE CABIN
ADD CONSTRAINT FK_DEPARTMENT_CABIN
FOREIGN KEY (id_department) REFERENCES DEPARTMENT (id);

ALTER TABLE CABIN
ADD CONSTRAINT FK_MUNICIPALITY_CABIN
FOREIGN KEY (id_municipality) REFERENCES MUNICIPALITY (id);

ALTER TABLE CITIZEN
ADD CONSTRAINT FK_DEPARTMENT_CITIZEN
FOREIGN KEY (id_department) REFERENCES DEPARTMENT (id);

ALTER TABLE CITIZEN
ADD CONSTRAINT FK_MUNICIPALITY_CITIZEN
FOREIGN KEY (id_municipality) REFERENCES MUNICIPALITY (id);

ALTER TABLE CITIZEN
ADD CONSTRAINT FK_TYPEcITIZEN_CITIZEN
FOREIGN KEY (id_type_citizen) REFERENCES TYPE_CITIZEN (id);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_CABIN_APPOINTMENT
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE APPOINTMENT
ADD CONSTRAINT FK_CITIZEN_APPOINTMENT
FOREIGN KEY (id_citizen) REFERENCES CITIZEN (dui);

--CREACION DE LLAVE FORANEA ENTRE DEPARTMENT AND MUNICIPALITY
ALTER TABLE MUNICIPALITY
ADD CONSTRAINT FK_DEPARTMENT_MUNICIPALITY
FOREIGN KEY (id_department) REFERENCES  DEPARTMENT (id);


--CREACION DE LAS LLAVES FORANEAS DE LA TABLA SESULTANDE DE LA TRASFORMACION N:N
ALTER TABLE MANAGERXCABIN
ADD CONSTRAINT FK_MANAGER_MANAGERXCABIN
FOREIGN KEY (id_manager) REFERENCES MANAGER (id);

ALTER TABLE MANAGERXCABIN
ADD CONSTRAINT FK_CABIN_MANAGERXCABIN
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

--CREACION DE LA LLLAVE FORANEA ENTRE LA TABLA MULTIEVALUADA DISEASES AND CITIZEN
ALTER TABLE DISEASES
ADD CONSTRAINT FK_CITIZEN_DISEASES
FOREIGN KEY (dui_citizen) REFERENCES CITIZEN (dui);

ALTER TABLE SIDE_EFFECTS
ADD CONSTRAINT FK_CITIZEN_SIDEEFFECTS
FOREIGN KEY (dui_citizen) REFERENCES CITIZEN (dui);


--- BANCO DE DATOS
-- DEPARTAMENTOS 
INSERT INTO DEPARTMENT VALUES('AHUACHAPAN')
INSERT INTO DEPARTMENT VALUES('SANTA ANA')
INSERT INTO DEPARTMENT VALUES('SONSONATE')
INSERT INTO DEPARTMENT VALUES('CHALATENANGO')
INSERT INTO DEPARTMENT VALUES('LA LIBERTAD')
INSERT INTO DEPARTMENT VALUES('SAN SALVADOR')
INSERT INTO DEPARTMENT VALUES('CUSCATLAN')
INSERT INTO DEPARTMENT VALUES('LA PAZ')
INSERT INTO DEPARTMENT VALUES('CABAÑAS')
INSERT INTO DEPARTMENT VALUES('SAN VICENTE')
INSERT INTO DEPARTMENT VALUES('USULUTAN')
INSERT INTO DEPARTMENT VALUES('SAN MIQUEL')
INSERT INTO DEPARTMENT VALUES('MORAZAN')
INSERT INTO DEPARTMENT VALUES('LA UNION')
-- SELECT * FROM DEPARTMENT;


-- MUNICIPIOS
INSERT INTO MUNICIPALITY VALUES ('AHUACHAPAN', 1)
INSERT INTO MUNICIPALITY VALUES ('APANECA', 1)
INSERT INTO MUNICIPALITY VALUES ('ATIQUIZAYA', 1)
INSERT INTO MUNICIPALITY VALUES ('CONCEPCION DE ATACO',1)
INSERT INTO MUNICIPALITY VALUES ('EL REFUGIO', 1)
INSERT INTO MUNICIPALITY VALUES ('GUAYMANGO', 1)
INSERT INTO MUNICIPALITY VALUES ('JUJUTLA', 1)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO MENENDEZ', 1)
INSERT INTO MUNICIPALITY VALUES ('SAN LORENZO', 1)
INSERT INTO MUNICIPALITY VALUES ('SAN PEDRO PUXTLA', 1)
INSERT INTO MUNICIPALITY VALUES ('TACUBA', 1)
INSERT INTO MUNICIPALITY VALUES ('TURIN', 1)
INSERT INTO MUNICIPALITY VALUES ('SANTA ANA', 2)
INSERT INTO MUNICIPALITY VALUES ('CANDELERA DE LA FRONTERA', 2)
INSERT INTO MUNICIPALITY VALUES ('COATEPEQUE', 2)
INSERT INTO MUNICIPALITY VALUES ('CHALCHUAPA', 2)
INSERT INTO MUNICIPALITY VALUES ('EL CONGO', 2)
INSERT INTO MUNICIPALITY VALUES ('EL PORVENIR', 2)
INSERT INTO MUNICIPALITY VALUES ('MASAUAT', 2)
INSERT INTO MUNICIPALITY VALUES ('METAPAN', 2)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO PAJONAL', 2)
INSERT INTO MUNICIPALITY VALUES ('SAN SEBASTIAN SALITRILLO', 2)
INSERT INTO MUNICIPALITY VALUES ('SANTA ROSA GUACHIPILIN', 2)
INSERT INTO MUNICIPALITY VALUES ('SANTIAGO DE LA FRONTERA', 2)
INSERT INTO MUNICIPALITY VALUES ('TEXISTEPEQUE', 2)
INSERT INTO MUNICIPALITY VALUES ('SONSONATE', 3)
INSERT INTO MUNICIPALITY VALUES ('ACAJUTLA', 3)
INSERT INTO MUNICIPALITY VALUES ('ARMENIA', 3)
INSERT INTO MUNICIPALITY VALUES ('CALUCO', 3)
INSERT INTO MUNICIPALITY VALUES ('CUISNAHUAT', 3)
INSERT INTO MUNICIPALITY VALUES ('IZALCO', 3)
INSERT INTO MUNICIPALITY VALUES ('JUAYUA', 3)
INSERT INTO MUNICIPALITY VALUES ('NAHUIZALCO', 3)
INSERT INTO MUNICIPALITY VALUES ('NAHULINGO', 3)
INSERT INTO MUNICIPALITY VALUES ('SALCOATITAN', 3)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO DEL MONTE', 3)
INSERT INTO MUNICIPALITY VALUES ('SAN JULIAN', 3)
INSERT INTO MUNICIPALITY VALUES ('SANTA CATARINA MASAHUAT', 3)
INSERT INTO MUNICIPALITY VALUES ('SANTA ISABEL ISHUATAN', 3)
INSERT INTO MUNICIPALITY VALUES ('SANTO DOMINGO', 3)
INSERT INTO MUNICIPALITY VALUES ('SONZACATE', 3)
INSERT INTO MUNICIPALITY VALUES ('CHALATENANGO', 4)
INSERT INTO MUNICIPALITY VALUES ('AGUA CALIENTE', 4)
INSERT INTO MUNICIPALITY VALUES ('ARCATAO', 4)
INSERT INTO MUNICIPALITY VALUES ('AZACUALPA', 4)
INSERT INTO MUNICIPALITY VALUES ('CANCASQUE', 4)
INSERT INTO MUNICIPALITY VALUES ('CITALA', 4)
INSERT INTO MUNICIPALITY VALUES ('COMALAPA', 4)
INSERT INTO MUNICIPALITY VALUES ('CONCEPCION QUEZALTEPEQUE', 4)
INSERT INTO MUNICIPALITY VALUES ('DULCE NOMBRE DE MARIA', 4)
INSERT INTO MUNICIPALITY VALUES ('EL CARRIZAL', 4)
INSERT INTO MUNICIPALITY VALUES ('EL PARAISO', 4)
INSERT INTO MUNICIPALITY VALUES ('LA LAGUNA', 4)
INSERT INTO MUNICIPALITY VALUES ('LA PALMA', 4)
INSERT INTO MUNICIPALITY VALUES ('LA REINA', 4)
INSERT INTO MUNICIPALITY VALUES ('LAS FLORES', 4)
INSERT INTO MUNICIPALITY VALUES ('LAS VUELTAS', 4)
INSERT INTO MUNICIPALITY VALUES ('NOMBRE DE JESUS', 4)
INSERT INTO MUNICIPALITY VALUES ('NUEVA CONCEPCION', 4)
INSERT INTO MUNICIPALITY VALUES ('NUEVA TRINIDAD', 4)
INSERT INTO MUNICIPALITY VALUES ('OJOS DE AGUA', 4)
INSERT INTO MUNICIPALITY VALUES ('POTONICO', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO DE LA CRUZ', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO LOS RANCHOS', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN FERNANDO', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO LEMPA', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO MORAZAN', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN IGNACIO', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN ISIDRO LABRADOR', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN LUIS DEL CARMEN', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN MIGUEL DE MERCEDES', 4)
INSERT INTO MUNICIPALITY VALUES ('SAN RAFAEL', 4)
INSERT INTO MUNICIPALITY VALUES ('SANTA RITA', 4)
INSERT INTO MUNICIPALITY VALUES ('TEJUTLA', 4)
INSERT INTO MUNICIPALITY VALUES ('SANTA TECLA', 5)
INSERT INTO MUNICIPALITY VALUES ('ANTIGUO CUSCATLAN', 5)
INSERT INTO MUNICIPALITY VALUES ('CIUDAD ARCE', 5)
INSERT INTO MUNICIPALITY VALUES ('COLON', 5)
INSERT INTO MUNICIPALITY VALUES ('COMASAGUA', 5)
INSERT INTO MUNICIPALITY VALUES ('CHILTIUPAN', 5)
INSERT INTO MUNICIPALITY VALUES ('HUIZUCAR', 5)
INSERT INTO MUNICIPALITY VALUES ('JAYAQUE', 5)
INSERT INTO MUNICIPALITY VALUES ('JICALAPA', 5)
INSERT INTO MUNICIPALITY VALUES ('LA LIBERTAD', 5)
INSERT INTO MUNICIPALITY VALUES ('NUEVO CUSCATLAN', 5)
INSERT INTO MUNICIPALITY VALUES ('OPICO', 5)
INSERT INTO MUNICIPALITY VALUES ('QUEZALTEPEQUE', 5)
INSERT INTO MUNICIPALITY VALUES ('SACACOYO', 5)
INSERT INTO MUNICIPALITY VALUES ('SAN JOSE VILLANUEVA', 5)
INSERT INTO MUNICIPALITY VALUES ('SAN MATIAS', 5)
INSERT INTO MUNICIPALITY VALUES ('SAN PABLO TACACHICO', 5)
INSERT INTO MUNICIPALITY VALUES ('TALNIQUE', 5)
INSERT INTO MUNICIPALITY VALUES ('TAMANIQUE', 5)
INSERT INTO MUNICIPALITY VALUES ('TEOTEPEQUE', 5)
INSERT INTO MUNICIPALITY VALUES ('TEPECOYO', 5)
INSERT INTO MUNICIPALITY VALUES ('ZARAGOZA', 5)
INSERT INTO MUNICIPALITY VALUES ('SAN SALVADOR', 6)
INSERT INTO MUNICIPALITY VALUES ('AGUILARES', 6)
INSERT INTO MUNICIPALITY VALUES ('APOPA', 6)
INSERT INTO MUNICIPALITY VALUES ('AYUTUXTEPEQUE', 6)
INSERT INTO MUNICIPALITY VALUES ('CUSCATANCIGO', 6)
INSERT INTO MUNICIPALITY VALUES ('DELGADO', 6)
INSERT INTO MUNICIPALITY VALUES ('EL PAISNAL', 6)
INSERT INTO MUNICIPALITY VALUES ('GUAZAPA', 6)
INSERT INTO MUNICIPALITY VALUES ('ILOPANGO', 6)
INSERT INTO MUNICIPALITY VALUES ('MEJICANOS', 6)
INSERT INTO MUNICIPALITY VALUES ('NEJAPA', 6)
INSERT INTO MUNICIPALITY VALUES ('PANCHIMALCO', 6)
INSERT INTO MUNICIPALITY VALUES ('ROSARIO DE MORA', 6)
INSERT INTO MUNICIPALITY VALUES ('SAN MARCOS', 6)
INSERT INTO MUNICIPALITY VALUES ('SAN MARTIN', 6)
INSERT INTO MUNICIPALITY VALUES ('SANTIAGO TEXACUANGOS', 6)
INSERT INTO MUNICIPALITY VALUES ('SANTO TOMAS', 6)
INSERT INTO MUNICIPALITY VALUES ('SOYAPANGO', 6)
INSERT INTO MUNICIPALITY VALUES ('TONACATEPEQUE', 6)
INSERT INTO MUNICIPALITY VALUES ('COJUTEPEQUE', 7)
INSERT INTO MUNICIPALITY VALUES ('CANDELARIA', 7)
INSERT INTO MUNICIPALITY VALUES ('EL CARMEN', 7)
INSERT INTO MUNICIPALITY VALUES ('EL ROSARIO', 7)
INSERT INTO MUNICIPALITY VALUES ('MONTE SAN JUAN', 7)
INSERT INTO MUNICIPALITY VALUES ('ORATORIO DE CONCEPCION', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN BARTOLOME PERULAPIA', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN CRISTOBAL', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN JOSE GUAYABAL', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN PEDRO PERULAPAN', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN RAFAEL CEDROS', 7)
INSERT INTO MUNICIPALITY VALUES ('SAN RAMON', 7)
INSERT INTO MUNICIPALITY VALUES ('SANTA CRUZ ANALQUITO', 7)
INSERT INTO MUNICIPALITY VALUES ('SANTA CRUZ MICHAPA', 7)
INSERT INTO MUNICIPALITY VALUES ('SUCHITOTO', 7)
INSERT INTO MUNICIPALITY VALUES ('TENANCINGO', 7)
INSERT INTO MUNICIPALITY VALUES ('ZACATECOLUCA', 8)
INSERT INTO MUNICIPALITY VALUES ('CUYULTITAN', 8)
INSERT INTO MUNICIPALITY VALUES ('EL ROSARIO', 8)
INSERT INTO MUNICIPALITY VALUES ('JERUSALEN', 8)
INSERT INTO MUNICIPALITY VALUES ('MERCEDES LA CEIBA', 8)
INSERT INTO MUNICIPALITY VALUES ('OLOCUILTA', 8)
INSERT INTO MUNICIPALITY VALUES ('PARAISO DE OSORIO', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO MASAHUAT', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN EMIGDIO', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO CHINAMECA', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN JUAN NONUALCO', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN JUAN TALPA', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN JUAN TEPEZONTES', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN LUIS TALPA', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN LUIS LA HERRADURA', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN MIGUEL TEPEZONTES', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN PEDRO MASAHUAT', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN PEDRO NONUALCO', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN RAFAEL OBRAJUELO', 8)
INSERT INTO MUNICIPALITY VALUES ('SANTA MARIA OSTUMA', 8)
INSERT INTO MUNICIPALITY VALUES ('SANTIAGO NONUALCO', 8)
INSERT INTO MUNICIPALITY VALUES ('TAPALHUACA', 8)
INSERT INTO MUNICIPALITY VALUES ('SAN JOSE',14)
INSERT INTO MUNICIPALITY VALUES ('SAN ALEJO',14)
INSERT INTO MUNICIPALITY VALUES ('POLOROS',14)
INSERT INTO MUNICIPALITY VALUES ('PASAQUINA',14)
INSERT INTO MUNICIPALITY VALUES ('NUEVA ESPARTA',14)
INSERT INTO MUNICIPALITY VALUES ('MEANGUERA DEL GOLFO',14)
INSERT INTO MUNICIPALITY VALUES ('LISLIQUE',14)
INSERT INTO MUNICIPALITY VALUES ('INTIPUCA',14)
INSERT INTO MUNICIPALITY VALUES ('EL SAUCE',14)
INSERT INTO MUNICIPALITY VALUES ('EL CARMEN',14)
INSERT INTO MUNICIPALITY VALUES ('CONCHAGUA',14)
INSERT INTO MUNICIPALITY VALUES ('CONCEPCION DEL ORIENTE',14)
INSERT INTO MUNICIPALITY VALUES ('BOLIVAR',14)
INSERT INTO MUNICIPALITY VALUES ('ANAMOROS',14)
INSERT INTO MUNICIPALITY VALUES ('LA UNION',14)
INSERT INTO MUNICIPALITY VALUES ('YOLOAIQUIN',13)
INSERT INTO MUNICIPALITY VALUES ('TOROLA',13)
INSERT INTO MUNICIPALITY VALUES ('SOCIEDAD',13)
INSERT INTO MUNICIPALITY VALUES ('SAN SIMON',13)
INSERT INTO MUNICIPALITY VALUES ('SENSEMBRA',13)
INSERT INTO MUNICIPALITY VALUES ('SAN ISIDRO',13)
INSERT INTO MUNICIPALITY VALUES ('SAN FERNANDO',13)
INSERT INTO MUNICIPALITY VALUES ('SAN CARLOS',13)
INSERT INTO MUNICIPALITY VALUES ('PERQUIN',13)
INSERT INTO MUNICIPALITY VALUES ('OSICALA',13)
INSERT INTO MUNICIPALITY VALUES ('MEANGUERA',13)
INSERT INTO MUNICIPALITY VALUES ('LOLOTIQUILLO',13)
INSERT INTO MUNICIPALITY VALUES ('JOCORO',13)
INSERT INTO MUNICIPALITY VALUES ('JOCOAITIQUE',13)
INSERT INTO MUNICIPALITY VALUES ('JOATECA',13)
INSERT INTO MUNICIPALITY VALUES ('GUATAJIAGUA',13)
INSERT INTO MUNICIPALITY VALUES ('GUALOCOCTI',13)
INSERT INTO MUNICIPALITY VALUES ('EL DIVISADERO',13)
INSERT INTO MUNICIPALITY VALUES ('DELICIAS DE CONCEPCION',13)
INSERT INTO MUNICIPALITY VALUES ('CHILANGA',13)
INSERT INTO MUNICIPALITY VALUES ('CORINTO',13)
INSERT INTO MUNICIPALITY VALUES ('CACAOPERA',13)
INSERT INTO MUNICIPALITY VALUES ('ARAMBALA',13)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO (GOTERA)',13)
INSERT INTO MUNICIPALITY VALUES ('ULUAZAPA',12)
INSERT INTO MUNICIPALITY VALUES ('SESORI',12)
INSERT INTO MUNICIPALITY VALUES ('SAN RAFAEL',12)
INSERT INTO MUNICIPALITY VALUES ('SAN LUIS DE LA REINA',12)
INSERT INTO MUNICIPALITY VALUES ('SAN JORGE',12)
INSERT INTO MUNICIPALITY VALUES ('SAN GERARDO',12)
INSERT INTO MUNICIPALITY VALUES ('SAN ANTONIO',12)
INSERT INTO MUNICIPALITY VALUES ('QUELEPA',12)
INSERT INTO MUNICIPALITY VALUES ('NUEVO EDEN DE SAN JUAN',12)
INSERT INTO MUNICIPALITY VALUES ('NUEVA GUADALUPE',12)
INSERT INTO MUNICIPALITY VALUES ('MONCAGUA',12)
INSERT INTO MUNICIPALITY VALUES ('LOLOTIQUE',12)
INSERT INTO MUNICIPALITY VALUES ('EL TRANSITO',12)
INSERT INTO MUNICIPALITY VALUES ('CHIRILAGUA',12)
INSERT INTO MUNICIPALITY VALUES ('CHINAMECA',12)
INSERT INTO MUNICIPALITY VALUES ('CHAPELTIQUE',12)
INSERT INTO MUNICIPALITY VALUES ('COMACARAN',12)
INSERT INTO MUNICIPALITY VALUES ('CIUDAD BARRIOS',12)
INSERT INTO MUNICIPALITY VALUES ('CAROLINA',12)
INSERT INTO MUNICIPALITY VALUES ('SAN MIGUEL',12)
INSERT INTO MUNICIPALITY VALUES ('SANTIAGO DE MARIA',11)
INSERT INTO MUNICIPALITY VALUES ('SANTA MARIA',11)
INSERT INTO MUNICIPALITY VALUES ('SANTA ELENA',11)
INSERT INTO MUNICIPALITY VALUES ('SAN FRANCISCO JAVIER',11)
INSERT INTO MUNICIPALITY VALUES ('SAN DIONISIO',11)
INSERT INTO MUNICIPALITY VALUES ('SAN BUENAVENTURA',11)
INSERT INTO MUNICIPALITY VALUES ('SAN AGUSTIN',11)
INSERT INTO MUNICIPALITY VALUES ('PUERTO EL TRIUNFO',11)
INSERT INTO MUNICIPALITY VALUES ('OZATLAN',11)
INSERT INTO MUNICIPALITY VALUES ('NUEVA GRANADA',11)
INSERT INTO MUNICIPALITY VALUES ('MERCEDES UMAÑA',11)
INSERT INTO MUNICIPALITY VALUES ('JUCUARAN',11)
INSERT INTO MUNICIPALITY VALUES ('JIQUILISCO',11)
INSERT INTO MUNICIPALITY VALUES ('ESTANZUELAS',11)
INSERT INTO MUNICIPALITY VALUES ('EREGUAYQUIN',11)
INSERT INTO MUNICIPALITY VALUES ('EL TRIUNFO',11)
INSERT INTO MUNICIPALITY VALUES ('CONCEPCION BATRES',11)
INSERT INTO MUNICIPALITY VALUES ('CALIFORNIA',11)
INSERT INTO MUNICIPALITY VALUES ('BERLIN',11)
INSERT INTO MUNICIPALITY VALUES ('ALEGRIA',11)
INSERT INTO MUNICIPALITY VALUES ('USULUTAN',11)
INSERT INTO MUNICIPALITY VALUES ('VERAPAZ',10)
INSERT INTO MUNICIPALITY VALUES ('TEPETITAN',10)
INSERT INTO MUNICIPALITY VALUES ('TECOLUCA',10)
INSERT INTO MUNICIPALITY VALUES ('SANTO DOMINGO',10)
INSERT INTO MUNICIPALITY VALUES ('SANTA CLARA',10)
INSERT INTO MUNICIPALITY VALUES ('SAN SEBASTIAN',10)
INSERT INTO MUNICIPALITY VALUES ('SAN LORENZO',10)
INSERT INTO MUNICIPALITY VALUES ('SAN ILDEFONSO',10)
INSERT INTO MUNICIPALITY VALUES ('SAN ESTEBAN CATARINA',10)
INSERT INTO MUNICIPALITY VALUES ('SAN CAYETANO ISTEPEQUE',10)
INSERT INTO MUNICIPALITY VALUES ('GUADALUPE',10)
INSERT INTO MUNICIPALITY VALUES ('APASTEPEQUE',10)
INSERT INTO MUNICIPALITY VALUES ('SAN VICENTE',10)
INSERT INTO MUNICIPALITY VALUES ('VICTORIA',9)
INSERT INTO MUNICIPALITY VALUES ('TEJUTEPEQUE',9)
INSERT INTO MUNICIPALITY VALUES ('SAN ISIDRO',9)
INSERT INTO MUNICIPALITY VALUES ('JUTIAPA',9)
INSERT INTO MUNICIPALITY VALUES ('ILOBASCO',9)
INSERT INTO MUNICIPALITY VALUES ('GUACOTECTI',9)
INSERT INTO MUNICIPALITY VALUES ('DOLORES',9)
INSERT INTO MUNICIPALITY VALUES ('CINQUERA',9)
INSERT INTO MUNICIPALITY VALUES ('SENSUNTEPEQUE',9)
-- SELECT * FROM MUNICIPALITY;


-- TIPO EMPLEADO
INSERT INTO TYPE_EMPLOYEE VALUES ('Gestor')
INSERT INTO TYPE_EMPLOYEE VALUES ('Vacunador')
INSERT INTO TYPE_EMPLOYEE VALUES ('Asistente de salud')
INSERT INTO TYPE_EMPLOYEE VALUES ('Encargado de limpieza')
-- SELECT * FROM TYPE_EMPLOYEE;

-- GESTORES
INSERT INTO MANAGER VALUES('LopezJo','afXpxOC')
INSERT INTO MANAGER VALUES('MelendezRi','OXMeLYI')
INSERT INTO MANAGER VALUES('AguirreAl','VTD65rO')
INSERT INTO MANAGER VALUES('VegaSa','wtSDMrb')
INSERT INTO MANAGER VALUES('GonzálezGe','ubBN9LP')
INSERT INTO MANAGER VALUES('Gestor', '123456')
-- SELECT * FROM MANAGER;

-- EMPLEADO
--- Gestores
INSERT INTO EMPLOYEE VALUES ('Joseline Amalia Pardo Lopez', 'Col San Ramón Pje 3 Lt 44, Quezaltepeque, La Libertad',
							'LopezJo001@gobierno.org.sv', 1, 1)
INSERT INTO EMPLOYEE VALUES ('Rina Diana Melendez Rojas', '27 ave Nte No 1331, apto 12 Urb. La Esperanza, San Salvador',
							'MelendezRi002@gobierno.org.sv', 1, 2)
INSERT INTO EMPLOYEE VALUES ('Alexander Aguirre Zarta', ' Col Gerardo Barrios Políg 5 No 5, Santa Ana',
							'AguirreAl003@gobierno.org.sv', 1, 3)
INSERT INTO EMPLOYEE VALUES ('Samarí  Vega  Salas', '7 Cl Pte Y 4 Av Sur No 12, Santa Ana',
							'VegaSa004@gobierno.org.sv', 1, 4)
INSERT INTO EMPLOYEE VALUES ('Geraldina de las Mercedes González Franco', 'Blvd San Bartolo Qta Las Delicias No 2 Ilop, Soyapango, San Salvador',
							'GonzálezGe005@gobierno.org.sv', 1, 5)
--- Vacunadores
INSERT INTO EMPLOYEE VALUES ('Pilar Correa Perez', 'Resid Sta Teresa 13 Cl Ote No 32 La Libertad',
							'CorreaPi006@gobierno.org.sv', 2, NULL)
INSERT INTO EMPLOYEE VALUES ('Yovir Rosania Ponce Morillo', 'Bo El Rosario 1 Av Nte No 206, Nueva Concepción, Chalatenango',
							'PonceYo007@gobierno.org.sv', 2, NULL)
INSERT INTO EMPLOYEE VALUES ('Patricia Elizabeth Castro Ochoa de Posada', 'Bo San Esteban Cl Libertad Pte, Texistepeque, Santa Ana',
							'Castro Pa008@gobierno.org.sv', 2, NULL)
INSERT INTO EMPLOYEE VALUES ('Ana Lissette Bran Solórzano', 'Ps Gral Escalón Cond Balam Quitzé No 23, San Salvador',
							'BranAn009@gobierno.org.sv', 2, NULL)
INSERT INTO EMPLOYEE VALUES ('Yadira Antonia  González Concepción', 'Cl Francisco Parrillas Y 4 Av Sur No 711, Nueva Concepción, Chalatenango',
							'GonzálezYa010@gobierno.org.sv', 2, NULL)

--- Asistentes de Salud
INSERT INTO EMPLOYEE VALUES ('Mónica Gabriela Silva Abrego', 'Cl. Gral. Menéndez 5-8, Bo. Concepción, La Unión',
							'SilvaMó011@gobierno.org.sv', 3, NULL)
INSERT INTO EMPLOYEE VALUES ('Mayra Teresita de Jesús  Sierra Rodríguez', 'Carrt Panamericana 500 Mts Al Nte De Metrocentro, San Miguel',
							'SierraMa012@gobierno.org.sv', 3, NULL)
INSERT INTO EMPLOYEE VALUES ('Elsa Villareal Mora', 'Urb Industial Sta Elena Cl Siemens No 54 Antgo Cusc, San Salvador',
							'VillarealEl013@gobierno.org.sv', 3, NULL)
INSERT INTO EMPLOYEE VALUES ('Nohora Elvira Díaz', 'Bo Los Remedios 1 Cl Ote, Sensuntepeque, Cabañas',
							'DíazNo014@gobierno.org.sv', 3, NULL)
INSERT INTO EMPLOYEE VALUES ('Thelma Alicia Lasso  Sánchez', 'Resid La Cima Iv Cl San Patricio Políg F No 29, San Salvador',
							'LassoTh016@gobierno.org.sv', 3, NULL)

--- Encargados de Limpieza
INSERT INTO EMPLOYEE VALUES ('Rosalba Del Carmen Garcés Molinar', 'Z Industrial Sta Elena Cl Chaparrastique No 34 Antgo Cusc, San Salvador',
							'GarcesRo017@gobierno.org.sv', 4, NULL)
INSERT INTO EMPLOYEE VALUES ('Militza Estela Agüero Ríos', ' Bo El Angel Cl Alberto Masferrer Ote No 6-1',
							'AgueroMi019@gobierno.org.sv', 4, NULL)
INSERT INTO EMPLOYEE VALUES ('Leticia Paola Gaona Gamarra', 'Bo Las Animas 1 Av Sur No 9, Chalchuapa, Santa Ana',
							'GaonaLe020@gobierno.org.sv', 4, NULL)
INSERT INTO EMPLOYEE VALUES ('Carmen Ivelisse Ureña', 'Urb Madre Selva Av El Espino No 56 Sta Elena, San Salvador',
							'UrenaCa022@gobierno.org.sv', 4, NULL)
INSERT INTO EMPLOYEE VALUES ('Leonidas Gutiérrez  Ávila', 'Cl José Matías Delgado No 3, Cojutepeque, San Salvador',
							'GutierrezLe018@gobierno.org.sv', 4, NULL)

-- CABINAS 
-- CABINAS LA LIBERTAD
INSERT INTO CABIN VALUES('cabinalbsv0001@gobierno.org.sv','Joseline Amalia Pardo Lopez',
						'Hosiptal Col Jard De La Sabana I Políg 3-C Sda 6 No 44','2314-9952',5,75)
INSERT INTO CABIN VALUES('cabinalbsv0002@gobierno.org.sv','Rina Diana Melendez Rojas',
						'Unidad de Salud 2 Cl Pte Y 6 Av Sur Plaza Novocentro Loc 30-C Sta Tecla','2385-9871',5,75)
INSERT INTO CABIN VALUES('cabinalbsv0003@gobierno.org.sv','Samarí  Vega  Salas',
						'Carrt Panamericana Bo El Rosario No 5-A, Ciudad Arce','2399-5214',5,77)
INSERT INTO CABIN VALUES('Unidad de Salud cabinalbsv0004@gobierno.org.sv','Geraldina de las Mercedes González Franco',
						'Hosiptal Jard De Merliot Cl Cuyagualo Políg L No 41','2325-2430',5,75)
INSERT INTO CABIN VALUES('cabinalbsv0005@gobierno.org.sv','Alexander Aguirre Zarta',
						'Unidad de Salud Nvl 1 Loc 2 Hiper Mall Las Cascadas Antgo Cusc','2356-7085',5,76)

-- CABINAS SAN SALVADOR						
INSERT INTO CABIN VALUES('cabinasssv0001@gobierno.org.sv','Alexander Aguirre Zarta',
						'Hosiptal Rosales Col San Francisco Av Las Dalias No 160','2378-7085',6,97)
INSERT INTO CABIN VALUES('cabinasssv0002@gobierno.org.sv','Samarí  Vega  Salas',
						'Unidad de Salud Comunitaria 5 Av Sur Edif Centroamérica No 328 Loc 1','2345-7085',6,97)
INSERT INTO CABIN VALUES('cabinasssv0003@gobierno.org.sv','Geraldina de las Mercedes González Franco',
						'Unidad de Salud Comunitaria Resid Sta Lucía Cl Ppal Políg M No 28 Ilop','2300-7085',6,114)
INSERT INTO CABIN VALUES('cabinasssv0004@gobierno.org.sv','Alexander Aguirre Zarta',
						'Unidad de Salud Comunitaria Bo. Distrito Comercial Central Cl Arce No 317','2310-7085',6,97)
INSERT INTO CABIN VALUES('cabinasssv0005@gobierno.org.sv','Rina Diana Melendez Rojas',
						'Unidad de Salud Comunitaria Bo. Distrito Comercial Central Cl Arce No 317','2310-7085',6,97)
--CABINAS AHUACHAPAN
INSERT INTO CABIN VALUES('cabinaahua0001@gobierno.org.sv','Soledad del Socorro Gonzales',
						'Hosiptal  El Centro Cl Litoral Fte Bco Agrícola ','2378-0007',1,1)
INSERT INTO CABIN VALUES('cabinaahua0002@gobierno.org.sv','Alexander Joaquin luna',
						'Unidad de Salud Comunitaria Bo El Centro 6 Cl Pte Y Av Fraancisco Menéndez Nte','2341-75281',1,3)
INSERT INTO CABIN VALUES('cabinaahua0003@gobierno.org.sv','Pedro Jose Flores Hernandez',
						'Hosiptal 10 Cl Pte No 2-6 2O Nvl Clínicas Médicasnuestra Señora De Lourdes','2145-8925',1,1)
INSERT INTO CABIN VALUES('cabinahua0004@gobierno.org.sv','Marta Beatriz Montes Aragon',
						'Unidad de Salud Comunitaria Bo El Calvario 6 Cl Pte # 3 18','2820-3655',1,2)
INSERT INTO CABIN VALUES('cabinahua0005@gobierno.org.sv','Esperanza Gloria de Dios',
						'Hosiptal Bo El Chile 3 Av Sur', '2100-0000',1,1)

--CABINAS SANTA ANA
INSERT INTO CABIN VALUES('cabinasntl0001@gobierno.org.sv','Maria Sofia Giron Paredes',
						'Hosiptal  Col Sta Marina 19 Av Nte No 17','2378-7357',2,13)
INSERT INTO CABIN VALUES('cabinasnt0002@gobierno.org.sv','Jose Feliciano Amador Sol',
						'Unidad de Salud Comunitaria 3 Av Sur No 21-B Ent 7 Y 9 Cl Ote','2341-75281',2,13)
INSERT INTO CABIN VALUES('cabinastn0003@gobierno.org.sv','Aniceto Molina Balboa',
						'Unidad de Salud Comunitaria 7 Av Sur No 36 Ent 9 Y 11 Cl Ote','2303-7075',2,13)
INSERT INTO CABIN VALUES('cabinasnt0004@gobierno.org.sv','Arial Joaquin Aquino',
						'Hosiptal Bo Sta Cruz Av Club De Leones Nte No 5, Chalchuapa','2310-3655',2,16)
INSERT INTO CABIN VALUES('cabinasntl0005@gobierno.org.sv','Esperanza Gloria de Dios',
						'Hosiptal Av Independencia Sur Ent 7 Y 9 Cl Pte', '2300-7085',2,13)
--CABINAS SONSOSNATE
INSERT INTO CABIN VALUES('cabinassn0001@gobierno.org.sv','Jose Andres Rojas Reyes',
						'Unidad de Salud Comunitaria Bo El Centro Av Claudia Lars','2198-7357',3,26)
INSERT INTO CABIN VALUES('cabinassn0002@gobierno.org.sv','Jose Feliciano Amador Sol',
						' Hosiptal Col Loma Linda Cl Ppal Y Cl Baleneario Agua Caliente, Caluco','2341-75281',3,29)
INSERT INTO CABIN VALUES('cabinassn0003@gobierno.org.sv','Aniceto Molina Balboa',
						'Unidad de Salud Comunitaria  Bo El Centro Av Morazán No 4-A','2203-7075',3,26)
INSERT INTO CABIN VALUES('cabinassn0004@gobierno.org.sv','Arial Joaquin Aquino',
						'Hosiptal Bo El Angel 6 Av Nte No 3-3','2923-8475',3,26)
INSERT INTO CABIN VALUES('cabinassn0005@gobierno.org.sv','Esperanza Gloria de Dios',
						'Unidad de Salud Comunitaria Av Independencia Sur Ent 7 Y 9 Cl Pte', '2300-9862',3,33)

--CABINAS CHALATENANGO
INSERT INTO CABIN VALUES('cabinachal0001@gobierno.org.sv','Katia Sofia Orellana Salas',
						'Unidad de Salud Comunitaria  Carrt Troncal Del Nte Km 79 La Palma, La Palma','2333-7357',4,54)
INSERT INTO CABIN VALUES('cabinassn0002@gobierno.org.sv','Emilio Alejandro Carbajal Figeroa',
						'Hosiptal Carrt A Km 77 1/2 Lotif Primavera','26661-75281',4,42)
INSERT INTO CABIN VALUES('cabinassn0003@gobierno.org.sv','Luz Alejandra Claros Guerra',
						'Unidad de Salud Comunitaria Bo El Centro Cl Ppal, San Francisco Morazán','2203-1111',4,67)
INSERT INTO CABIN VALUES('cabinassn0004@gobierno.org.sv','leo Armando Estrada Oliva',
						'Unidad de Salud Comunitaria Bo El Centro Cl San Martín No 14','2993-8475',4,42)
INSERT INTO CABIN VALUES('cabinassn0005@gobierno.org.sv','Esperanza Gloria de Dios',
						' Hosiptal Bo El Rosario 1 Av Nte No 206, Nueva Concepción', '2355-9862',4,59)
--CABINAS CUSCATLAN
INSERT INTO CABIN VALUES('cabinacus0001@gobierno.org.sv','Rosa Anastacia Uzumaki Uchiha',
						' Hosiptal Bo Concepción Av 15 De Septiembre No 85, Cuscatlán','2378-7995',7,130)
INSERT INTO CABIN VALUES('cabinacusv0002@gobierno.org.sv','Samarí  Vega  Salas',
						'Unidad de Salud Comunitaria Bo San Juan 6 Cl Ote No 5, Cuscatlán','2335-7085',7,116)
INSERT INTO CABIN VALUES('cabinacus0003@gobierno.org.sv','Kevin Alexander Padilla',
						'Hosiptal Bo San Juan Av Rafael Cabrera No 13, Cuscatlán','2400-4085',7,116)
INSERT INTO CABIN VALUES('cabinacus0004@gobierno.org.sv','Allan Daniel Delgado Roble',
						'Unidad de Salud Comunitaria Carrt Panamericna Bo Concepción No 6, Cuscatlán','2310-7885',7,116)
INSERT INTO CABIN VALUES('cabinacus0005@gobierno.org.sv','Dinora Maria Melendez Rojas',
						' Unidad de Salud Comunitaria Bo Concepción Av 15 De Septiembre No 4, Cuscatlán','2890-7085',7,130)

-- CABINAS LA PAZ
INSERT INTO CABIN VALUES('cabinalpz0001@gobierno.org.sv','Yuri Miquel Aleman',
						'Hosiptal Bo El Calvario Cl Ppal','2425-9586',8,143)
INSERT INTO CABIN VALUES('cabinalpz0002@gobierno.org.sv','Brenda Eliza Turcios',
						'Unidad de Salud Comunitaria Col Altamira Bl A Pje Los Pinos','2335-7085',8,133)
INSERT INTO CABIN VALUES('cabinalpz0003@gobierno.org.sv','Melvin Enrique Palma',
						'Hosiptal Bo El Calvario Cl Ppal','2865-4085',8,143)
INSERT INTO CABIN VALUES('cabinalpz0004@gobierno.org.sv','Erick josue Hermoso Belloso',
						'Unidad de Salud Comunitaria Av. José Matías Delgado # 1, Barrio El Centro','23109-5325',8,137)
INSERT INTO CABIN VALUES('cabinalpz0005@gobierno.org.sv','Eugenia del Carmen Solorzano',
						'Hosiptal Autop a Comalapa Km 28 1/2 Crío El Carmen Loc 1','2896-2165',8,137)

--CABINAS CABAÑAS 
INSERT INTO CABIN VALUES('cabinacbñ0001@gobierno.org.sv','Camilo jose Sexto',
						'Unidad de Salud Comunitaria Bo El Calvario Cl Ppal Bo Sta Bárbara 10 Av Sur No 3','2425-9586',9,255)
INSERT INTO CABIN VALUES('cabinacbñ0002@gobierno.org.sv','Ricardo Eduardo Montaner',
						' Hosiptal Bo El Centro Av Carlos Bonilla No 1','2335-7085',9,251)
INSERT INTO CABIN VALUES('cabinacbñ0003@gobierno.org.sv','Enrique Josue Iglesias',
						' Unidad de Salud Comunitaria Cl San Antonio Abad Pje Valdivieso No 5','2265-8474',9,255)
INSERT INTO CABIN VALUES('cabinacnñ0004@gobierno.org.sv','Evaluna Britany Montaner ',
						'  Hosiptal Bo El Centro 3 Cl Ote No 31','23109-5325',9,251)
INSERT INTO CABIN VALUES('cabinacbñ0005@gobierno.org.sv','Francisco Gabriel Lozano',
						'Unidad de Salud Comunitaria Cl San Antonio Abad Pje Valdivieso No 5','2896-2165',9,250)

--CABINAS SAN VICENTE
INSERT INTO CABIN VALUES('cabinasvc0001@gobierno.org.sv','Yesica Teresa Oliva',
						' Hosiptal  Bo Las Flores Av Benjamín E Valiente S','2725-9586',10,236)
INSERT INTO CABIN VALUES('cabinasvc0002@gobierno.org.sv','Karen Ivette Montano',
						' Unidad de Salud Comunitaria Blvd Hugo Chávez Cl Francisco Menéndez No 1','2135-7085',10,239)
INSERT INTO CABIN VALUES('cabinasvc0003@gobierno.org.sv','Rocio Zuniga',
						' Hosiptal Bo EL Calvario 1 Cl Pte No 31','2514-9578',10,240)
INSERT INTO CABIN VALUES('cabinasvc0004@gobierno.org.sv','Daniela Iris Cornejo ',
						' Unidad de Salud Comunitaria Urb Los Angeles Cl Ppal Pje A No 1-A','2969-5325',10,234)
INSERT INTO CABIN VALUES('cabinasvc0005@gobierno.org.sv','Gerardo Perez Zelaya',
						' Hosiptal 74 Av Sur No 104 Ent 29 Y 31 Cl Pte','2756-2165',10,238)

--CABINAS USULUTAN
INSERT INTO CABIN VALUES('cabinausl0001@gobierno.org.sv','Juana de los Angeles',
						'Hosiptal Col Magaña 23 Cl Ote Y 16 Av Nte No 803','2665-9586',11,233)
INSERT INTO CABIN VALUES('cabinausl0002@gobierno.org.sv','Olinda Noemi Marroquin',
						' Unidad de Salud Comunitaria Bo El Angel 10 Av Nte No 4-3','2954-7085',11,215)
INSERT INTO CABIN VALUES('cabinausl0003@gobierno.org.sv','Julio Cesar Bailon',
						' Unidad de Salud Comunitaria   4 Av Sur No 3-6 B','2248-9576',10,217)
INSERT INTO CABIN VALUES('cabinausl0004@gobierno.org.sv','Oscar Enrique Duran ',
						'Unidad de Salud Comunitaria Col Miramonte Av Sierra Nevada Edif C C No 704','27549-5325',11,231)
INSERT INTO CABIN VALUES('cabinausl0005@gobierno.org.sv','Fatima Rocio Perez',
						' Hosiptal Urb Jard De Guadalupe Av Río Mississipi No 1','2006-2005',11,232)
--CABINAS SAN MIQUEL
INSERT INTO CABIN VALUES('cabinasmq0001@gobierno.org.sv','Grecia Melanie Ventura',
						' Hosiptal  Bo Lourdes Cl Delgado Pje Josefina No 109','2665-9586',12,194) 
INSERT INTO CABIN VALUES('cabinasmq0002@gobierno.org.sv','Fernanda Batriz Mendoza',
						' Unidad de Salud Comunitaria Bo San José Av Silvestre De Jesús Díaz No 57','2954-7085',12,196)
INSERT INTO CABIN VALUES('cabinasmq0003@gobierno.org.sv','Jorge Enrique Palma',
						' Hosiptal  Av San Martín No 2-5','2136-8574',12,197)
INSERT INTO CABIN VALUES('cabinasmq0004@gobierno.org.sv','Camila Maria Castañeda',
						' Unidad de Salud Comunitaria  Av Morazán No 4-8','27549-5325',12,202)
INSERT INTO CABIN VALUES('cabinasmq0005@gobierno.org.sv','Guadalupe Ivannia Zelanda',
						' Hosiptal 6 Cl Ote No 106','2006-2005',12,212)

--CABINA MORAZAN
INSERT INTO CABIN VALUES('cabinamrz0001@gobierno.org.sv','Cristan Alexander Flores',
						' Hosiptal  Av Fray Felipe De Jesús Moraga Sur Ent 25 Y 27 Cl Pte','2665-6286',13,168)
INSERT INTO CABIN VALUES('cabinamrz0002@gobierno.org.sv','jonathan Inocente',
						' Unidad de Salud Comunitaria Cl Constitución Políg K No 4 Cdad Satélite','2324-7085',13,170)
INSERT INTO CABIN VALUES('cabinamrz0003@gobierno.org.sv','Lilian Mariana Olmedo',
						' Hosiptal  Bo San Antonio Fnl 4 Cl Pte','2564-8595',13,192)
INSERT INTO CABIN VALUES('cabinamrz0004@gobierno.org.sv','Jennifer Batriz Flores',
						' Hosiptal Col Flor Blanca Cl El Progreso 51 Av Sur No 2647','2354-9865',13,177)
INSERT INTO CABIN VALUES('cabinamrz0005@gobierno.org.sv','Andrea Alejandra Girasol',
						'Unidad de Salud Comunitaria Bo La Cruz Cl José Simeón Cañas No 25','2536-8978',13,190)

--CABINAS LA UNION

INSERT INTO CABIN VALUES('cabinalun0001@gobierno.org.sv','Samuel Antonio Constanza',
						'Hosiptal Col Las Delicias Del Nte Pje Cantizano No 3','2645-6286',14,157) 
INSERT INTO CABIN VALUES('cabinalun0002@gobierno.org.sv','Cesar Chavez LIima',
						' Unidad de Salud Comunitaria Av Independencia Sur y 27 Cl Pte','2324-6666',14,164)
INSERT INTO CABIN VALUES('cabinalun0003@gobierno.org.sv','Berta Elena Hernandez',
						'Unidad de Salud Comunitaria Bo El Centro 2 Av Sur Fte Mcdo Mpal ','2364-8595',14,168)
INSERT INTO CABIN VALUES('cabinalun0004@gobierno.org.sv','Alba Cristina Siman',
						'Hosiptal Colonia y Cl Roma No 156','2354-9865',14,163)
INSERT INTO CABIN VALUES('cabinalun0005@gobierno.org.sv','Marco Tulio Miranda',
						'Hosiptal 9 Av Sur No 2-9','2698-1200',14,154)

-- TYPE CITIZEN
INSERT INTO TYPE_CITIZEN VALUES ('Ninguno')
INSERT INTO TYPE_CITIZEN VALUES ('Adulto mayor de 60 años')
INSERT INTO TYPE_CITIZEN VALUES ('Personal del sistema integrado de salud')
INSERT INTO TYPE_CITIZEN VALUES ('PNC')
INSERT INTO TYPE_CITIZEN VALUES ('Fuerza Armada')
INSERT INTO TYPE_CITIZEN VALUES ('Cuerpos de socorro')
INSERT INTO TYPE_CITIZEN VALUES ('Personal de fronteras')
INSERT INTO TYPE_CITIZEN VALUES ('Persona mayor de 18 años con enfermedades no transmisibles')
INSERT INTO TYPE_CITIZEN VALUES ('Discacidad motora')
INSERT INTO TYPE_CITIZEN VALUES ('Personal del gobierno central')


-- COMPROBAR DATOS DE TABLAS
-- SELECT * FROM TYPE_CITIZEN;
-- SELECT * FROM APPOINTMENT;
-- SELECT * FROM CITIZEN;
-- SELECT * FROM DEPARTMENT;
-- SELECT * FROM MUNICIPALITY;
-- SELECT * FROM DISEASES;
-- SELECT * FROM CABIN;
-- SELECT * FROM MANAGERXCABIN;
-- SELECT * FROM SIDE_EFFECTS;

DROP PROCEDURE DashboardData
CREATE PROC DashboardData
@totalPeople1Dossis INT OUT,
@totalPeople2Dossis INT OUT,
@totalPeopleVaccinated INT OUT
AS 

-- PROCEDIMIENTOS PARA LOS GRAFICOS
-- DOSIS DADAS
-- PRIMERA DOSIS 
SET @totalPeople1Dossis = (SELECT SUM(PRIMERA_DOSIS_TOTAL.PriDosisAplicadas) AS TotalPersonasVacunadasPrimeraDosis
FROM(
	SELECT COUNT(id_citizen) 'PriDosisAplicadas'
	FROM APPOINTMENT
	WHERE hour_arrived IS NOT NULL  
	GROUP BY  id_citizen
	HAVING COUNT(id_citizen) = 1 
	)PRIMERA_DOSIS_TOTAL
GROUP BY PRIMERA_DOSIS_TOTAL.PriDosisAplicadas)

-- SEGUNDA DOSIS
SET @totalPeople2Dossis = (SELECT COUNT(SEGUNDA_DOSIS_TOTAL.SegDosisAplicadas) AS TotalPersonasVacunadasSegundaDosis
FROM(
	SELECT COUNT(id_citizen) 'SegDosisAplicadas'
	FROM APPOINTMENT
	WHERE hour_arrived IS NOT NULL  
	GROUP BY  id_citizen
	HAVING COUNT(id_citizen) = 2
	)SEGUNDA_DOSIS_TOTAL
GROUP BY SEGUNDA_DOSIS_TOTAL.SegDosisAplicadas)

--TOTAL DOSIS 
SET @totalPeopleVaccinated = (
				SELECT COUNT(id_appointment) 'DosisSuministradas'
				FROM APPOINTMENT
				WHERE hour_arrived IS NOT NULL
				)
GO



-- EFECTOS SECUNDARIOS 
CREATE PROC SideEffectShowed
AS
SELECT side_effect 'Efecto_secundario_sufrido', COUNT(side_effect) AS 'Ciudadanos'
FROM SIDE_EFFECTS
GROUP BY side_effect
ORDER BY COUNT(side_effect) DESC
GO

-- TIEMPO DEL ESPERA DE VACUNACION
ALTER PROC MinutesRanges
AS
SELECT  DETALLE_FINAL.[Rangos de tiempo], SUM(DETALLE_FINAL.Personas_atendidas) 'Personas atendidas'
FROM (
			SELECT 
				CASE 
			WHEN DETALLE_TIEMPO.Minutos_Esperados <= 15   THEN 'Menos de 15 minutos'
			WHEN DETALLE_TIEMPO.Minutos_Esperados > 15 AND DETALLE_TIEMPO.Minutos_Esperados <= 30 THEN 'Entre 15 y 30 Minutos'
			WHEN DETALLE_TIEMPO.Minutos_Esperados  > 30 AND DETALLE_TIEMPO.Minutos_Esperados <= 60 THEN 'Entre 30 y 60 Minutos'
			WHEN DETALLE_TIEMPO.Minutos_Esperados  > 60 THEN 'Más de 60 minutos'
			END AS 'Rangos de tiempo',
			COUNT(DETALLE_TIEMPO.Minutos_Esperados) 'Personas_atendidas'
			FROM (
					SELECT hour_arrived, hour_vaccunated, DATEDIFF(MINUTE, hour_arrived, hour_vaccunated) 'Minutos_Esperados'
					FROM APPOINTMENT
					WHERE hour_arrived IS NOT NULL
					)DETALLE_TIEMPO
			GROUP BY DETALLE_TIEMPO.Minutos_ESPERADOS
					)DETALLE_FINAL
GROUP BY DETALLE_FINAL.[Rangos de tiempo]
GO
